language: php
sudo: required
dist: trusty
group: edge

php:
  - hhvm
  - hhvm-nightly

before_script: composer install

matrix:
  allow_failures:
  - php: hhvm-nightly


script:
  - composer run-script tests
